import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const cabinetGrotesk = localFont({
  src: '../app/assets/fonts/CabinetGrotesk-Regular.otf',
  variable:"--font-cabinetGrotesk",
  display: "swap",
})
const magison = localFont({
  src: '../app/assets/fonts/MAGISON.ttf',
  variable:"--font-magison",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable}  ${magison.variable} antialiased bg-white `}
      >
        {children}
      </body>
    </html>
  );
}
