import type { Metadata } from "next";
import SellerShell from "./SellerShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{ background: "#FFF6F6" }}
      className={`h-screen antialiased overflow-hidden`}
    >
      <SellerShell>{children}</SellerShell>
    </div>
  );
}
